version: '3.8'

services:
  backend:
    build: 
      context: ./mindfulai-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./mindfulai-backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped 